#!/usr/bin/env python3
"""Render report.md from a results.json produced by run.py.

Usage: python3 bench/agent/report.py bench/agent/results/<date>
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

CATEGORIES = ("conceptual", "structural", "exact")
NATIVE = ("Read", "Grep", "Glob", "Bash", "Skill")
SQ_PREFIX = "mcp__semantiq__"
CLI_RE = re.compile(
    r"\bsemantiq\s+(search|refs|deps|explain|impact|calls|hierarchy|dead-code|map|index|stats)\b"
)


def semantiq_ops(r):
    """Semantiq operations of a run: MCP tool calls (`mcp:<tool>`), CLI
    subcommands run through Bash (`cli:<cmd>`) and semantiq skill loads."""
    ops = []
    for c in r["tool_calls"]:
        name = c["name"]
        if name.startswith(SQ_PREFIX):
            ops.append("mcp:" + name.removeprefix(SQ_PREFIX))
        elif name == "Bash":
            ops += ["cli:" + m for m in CLI_RE.findall(c["input"])]
        elif name == "Skill" and "semantiq" in c["input"]:
            ops.append("skill:semantiq")
    return ops


def _mean(xs):
    xs = [x for x in xs if x is not None]
    return sum(xs) / len(xs) if xs else None


def _fmt(x, digits=0, pct=False):
    if x is None:
        return "–"
    if pct:
        return f"{100 * x:.0f}%"
    if digits == 0:
        return f"{x:,.0f}".replace(",", " ")
    return f"{x:.{digits}f}"


def _delta(a, b):
    if a in (None, 0) or b is None:
        return "–"
    return f"{100 * (b - a) / a:+.0f}%"


def _duration_s(r):
    if r.get("duration_ms") is not None:
        return r["duration_ms"] / 1000
    return r.get("wall_seconds")


def _tool_counts(r):
    return Counter(c["name"] for c in r["tool_calls"])


def _valid(runs):
    return [r for r in runs if not r.get("invalid")]


def aggregate(runs):
    runs = _valid(runs)
    if not runs:
        return None
    tc = [len(r["tool_calls"]) for r in runs]
    sq = [len([o for o in semantiq_ops(r) if not o.startswith("skill:")]) for r in runs]
    return {
        "n": len(runs),
        "success": _mean([1.0 if r["score"]["success"] else 0.0 for r in runs]),
        "recall": _mean([r["score"]["recall"] for r in runs]),
        "precision": _mean([r["score"]["precision"] for r in runs]),
        "tokens_in": _mean([r["tokens_in"] for r in runs]),
        "tokens_out": _mean([r["tokens_out"] for r in runs]),
        "cost": _mean([r.get("cost_usd") for r in runs]),
        "tools": _mean(tc),
        "sq_tools": _mean(sq),
        "turns": _mean([r.get("num_turns") for r in runs]),
        "first_context": _mean([r.get("first_context_tokens") for r in runs]),
        "duration": _mean([_duration_s(r) for r in runs]),
    }


AGG_HEADER = (
    "| {first} | Config | Runs | Success | Recall | Precision | Tokens in | Tokens out "
    "| Cost (USD) | Tool calls | of which semantiq | Duration (s) |\n"
    "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"
)


def _agg_row(label, config, a):
    if a is None:
        return f"| {label} | {config} | 0 | – | – | – | – | – | – | – | – | – |"
    return (
        f"| {label} | {config} | {a['n']} | {_fmt(a['success'], pct=True)} | "
        f"{_fmt(a['recall'], 2)} | {_fmt(a['precision'], 2)} | {_fmt(a['tokens_in'])} | "
        f"{_fmt(a['tokens_out'])} | {_fmt(a['cost'], 3)} | {_fmt(a['tools'], 1)} | "
        f"{_fmt(a['sq_tools'], 1)} | {_fmt(a['duration'], 0)} |"
    )


def _delta_row(label, config, base, other):
    if base is None or other is None:
        return None
    return (
        f"| {label} | Δ {config} vs baseline | | "
        f"{(other['success'] - base['success']) * 100:+.0f} pts | "
        f"{other['recall'] - base['recall']:+.2f} | "
        f"{(other['precision'] or 0) - (base['precision'] or 0):+.2f} | "
        f"{_delta(base['tokens_in'], other['tokens_in'])} | "
        f"{_delta(base['tokens_out'], other['tokens_out'])} | "
        f"{_delta(base['cost'], other['cost'])} | {_delta(base['tools'], other['tools'])} | | "
        f"{_delta(base['duration'], other['duration'])} |"
    )


def render(results: dict, suites: list[dict] | None = None) -> str:
    meta, runs = results["meta"], results["runs"]
    configs = meta["configs"]
    prompts = {}
    for s in suites or []:
        for t in s["tasks"]:
            prompts[t["id"]] = t["prompt"]

    out = []
    out.append(f"# Agent benchmark — Claude Code with vs without Semantiq ({meta['date'][:10]})\n")
    out.append("Generated by `bench/agent/run.py` / `report.py`. Raw data: `results.json` "
               "(one record per run, with tool calls, usage and final answer).\n")
    out.append("## Setup\n")
    out.append(f"- Model: `{meta['model']}`" + (f", effort `{meta['effort']}`" if meta.get("effort") else ""))
    out.append(f"- Claude Code: `{meta.get('claude_version')}`; semantiq: `{meta.get('semantiq_version')}` "
               "(release, `--features semantiq-embeddings/onnx`)")
    out.append(f"- Configs: {', '.join(configs)}; repetitions: {meta['reps']}; parallel runs: {meta['jobs']}")
    out.append("- Native tools in both configs: Read, Grep, Glob, Bash (read-only allowlist, "
               "`--permission-mode dontAsk`); semantiq config adds only `mcp__semantiq__*`.")
    out.append("- Agent docs (CLAUDE.md, AGENTS.md, .claude/) "
               + ("kept" if meta.get("keep_agent_docs") else "removed") + " from the checkouts.")
    if meta.get("cli_skill"):
        cs = meta["cli_skill"]
        out.append(f"- cli-skill: CLI `{cs['cli_version']}` (`{cs['cli_bin']}`), skill SKILL.md "
                   f"sha256 `{cs['skill_sha256'][:12]}`")
    for name, repo in meta["repos"].items():
        idx = meta.get("index", {}).get(name)
        idx_txt = ""
        if idx:
            secs = "reused" if idx.get("reused") else f"{idx['seconds']} s"
            idx_txt = f"; index build {secs}, DB {idx['db_bytes'] / 1e6:.1f} MB"
        out.append(f"- Repo `{name}` @ `{repo['commit'][:12]}` ({repo['source']}){idx_txt}")
    for key, idx in meta.get("index", {}).items():
        if key not in meta["repos"] and not idx.get("reused"):
            out.append(f"- Index `{key}`: {idx['seconds']} s, DB {idx['db_bytes'] / 1e6:.1f} MB")
    out.append("")
    out.append("Tokens in = input + cache creation + cache read (everything the model read). "
               "Cost is the API-equivalent `total_cost_usd` reported by Claude Code. Duration is "
               "Claude Code's `duration_ms`. Success = recall ≥ task threshold and precision ≥ 0.5 "
               "on the `FINAL:` list.\n")

    invalid = [r for r in runs if r.get("invalid")]
    if invalid:
        out.append(f"**{len(invalid)} invalid run(s) excluded** (semantiq server not connected): "
                   + ", ".join(r["key"] for r in invalid) + "\n")

    by = defaultdict(list)
    for r in runs:
        by[(r["config"], None, None)].append(r)
        by[(r["config"], r["category"], None)].append(r)
        by[(r["config"], None, r["repo"])].append(r)
        by[(r["config"], r["category"], r["repo"])].append(r)

    out.append("## Overall\n")
    out.append(AGG_HEADER.format(first="Scope"))
    for c in configs:
        out.append(_agg_row("all", c, aggregate(by[(c, None, None)])))
    for c in configs:
        if c != "baseline" and "baseline" in configs:
            d = _delta_row("all", c, aggregate(by[("baseline", None, None)]), aggregate(by[(c, None, None)]))
            if d:
                out.append(d)
    out.append("")

    out.append("## By category\n")
    out.append(AGG_HEADER.format(first="Category"))
    for cat in CATEGORIES:
        aggs = {c: aggregate(by[(c, cat, None)]) for c in configs}
        if not any(aggs.values()):
            continue
        for c in configs:
            out.append(_agg_row(cat, c, aggs[c]))
        for c in configs:
            if c != "baseline" and "baseline" in aggs:
                d = _delta_row(cat, c, aggs["baseline"], aggs[c])
                if d:
                    out.append(d)
    out.append("")

    repos = sorted({r["repo"] for r in runs})
    if len(repos) > 1:
        out.append("## By repository and category\n")
        out.append(AGG_HEADER.format(first="Repo / category"))
        for repo in repos:
            for cat in (None,) + CATEGORIES:
                aggs = {c: aggregate(by[(c, cat, repo)]) for c in configs}
                if not any(aggs.values()):
                    continue
                for c in configs:
                    out.append(_agg_row(f"{repo} / {cat or 'all'}", c, aggs[c]))
        out.append("")

    out.append("## Per task\n")
    head = "| Task | Category |"
    sep = "|---|---|"
    for c in configs:
        head += f" {c}: ok | recall/prec | tools | tokens in | s |"
        sep += "---:|---:|---:|---:|---:|"
    out.append(head)
    out.append(sep)
    tasks = sorted({(r["repo"], r["task_id"], r["category"]) for r in runs},
                   key=lambda t: (t[0], CATEGORIES.index(t[2]), t[1]))
    for repo, tid, cat in tasks:
        row = f"| `{tid}` | {cat} |"
        for c in configs:
            rs = _valid([r for r in runs if r["task_id"] == tid and r["config"] == c])
            if not rs:
                row += " – | – | – | – | – |"
                continue
            ok = sum(1 for r in rs if r["score"]["success"])
            a = aggregate(rs)
            sq = f" ({_fmt(a['sq_tools'], 0)} sq)" if c.startswith("semantiq") else ""
            row += (f" {ok}/{len(rs)} | {_fmt(a['recall'], 2)}/{_fmt(a['precision'], 2)} | "
                    f"{_fmt(a['tools'], 0)}{sq} | {_fmt(a['tokens_in'])} | {_fmt(a['duration'], 0)} |")
        out.append(row)
    out.append("")

    out.append("## Tool usage\n")
    out.append("Mean calls per run. `semantiq ops` counts MCP semantiq tools and `semantiq` CLI "
               "commands run through Bash (the latter are also counted under Bash).\n")
    names = list(NATIVE)
    out.append("| Config | " + " | ".join(names) + " | semantiq ops | Initial context (tokens) |")
    out.append("|---|" + "---:|" * (len(names) + 2))
    for c in configs:
        rs = _valid(by[(c, None, None)])
        if not rs:
            continue
        cells = [_fmt(_mean([_tool_counts(r).get(n, 0) for r in rs]), 1) for n in names]
        a = aggregate(rs)
        out.append(f"| {c} | " + " | ".join(cells)
                   + f" | {_fmt(a['sq_tools'], 1)} | {_fmt(a['first_context'])} |")
    out.append("")
    out.append("Initial context = tokens of the first model request (system prompt, tool "
               "definitions or skill listing, task prompt): the fixed price paid on every turn.\n")

    sq_configs = [c for c in configs if c != "baseline"]
    if sq_configs:
        out.append("### Semantiq operations actually used\n")
        op_counter = Counter()
        for c in sq_configs:
            sq_runs = _valid(by[(c, None, None)])
            used = sum(1 for r in sq_runs
                       if any(not o.startswith("skill:") for o in semantiq_ops(r)))
            for r in sq_runs:
                op_counter.update(semantiq_ops(r))
            out.append(f"- `{c}`: {used}/{len(sq_runs)} runs used semantiq at least once.")
        out.append("")
        out.append("| Operation | " + " | ".join(f"{c}: calls | {c}: runs" for c in sq_configs) + " |")
        out.append("|---|" + "---:|---:|" * len(sq_configs))
        for op, _ in op_counter.most_common():
            cells = []
            for c in sq_configs:
                rs = _valid(by[(c, None, None)])
                cells += [str(sum(semantiq_ops(r).count(op) for r in rs)),
                          str(sum(1 for r in rs if op in semantiq_ops(r)))]
            out.append(f"| `{op}` | " + " | ".join(cells) + " |")
        out.append("")

    failures = [r for r in runs if not r["score"]["success"]]
    if failures:
        out.append("## Failed runs\n")
        out.append("| Run | Recall | Precision | Missed | Extra entries | FINAL found |")
        out.append("|---|---:|---:|---|---|---|")
        for r in failures:
            s = r["score"]
            extra = ", ".join(f"`{x}`" for x in s["extra"][:4]) + (" …" if len(s["extra"]) > 4 else "")
            out.append(f"| `{r['key']}` | {_fmt(s['recall'], 2)} | {_fmt(s['precision'], 2)} | "
                       f"{', '.join(s['missed']) or '–'} | {extra or '–'} | "
                       f"{'yes' if s['final_found'] else 'no'} |")
        out.append("")

    if prompts:
        out.append("## Task prompts\n")
        for repo, tid, cat in tasks:
            out.append(f"- `{tid}` ({cat}): {prompts.get(tid, '')}")
        out.append("")
    return "\n".join(out)


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    out = Path(argv[0])
    results = json.loads((out / "results.json").read_text())
    tasks_dir = Path(__file__).resolve().parent / "tasks"
    suites = [json.loads(p.read_text()) for p in sorted(tasks_dir.glob("*.json"))]
    (out / "report.md").write_text(render(results, suites))
    print(out / "report.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
