//! Compact JSON schemas for the tool definitions.
//!
//! `tools/list` is sent to the model on every turn, so its schemas are kept to
//! what a client needs to call the tools and validate their results: input
//! schemas keep the parameter descriptions, output schemas keep only the
//! structure. Number formats, bounds and titles generated by schemars are
//! dropped, and `Option` fields are typed without `null`: optional parameters
//! are simply left out, and every optional output field is skipped when empty
//! (`skip_serializing_if`). Definitions used once are inlined where they are
//! referenced. The schemas stay valid JSON Schema 2020-12.

use rmcp::handler::server::common::{schema_for_input, schema_for_output};
use rmcp::model::JsonObject;
use rmcp::schemars::JsonSchema;
use serde_json::Value;
use std::sync::Arc;

/// Keywords dropped from every schema: informative only, they do not change
/// which values are accepted for our types (`format: uint` and `minimum: 0`
/// on `usize`, `format: float` on `f32`).
const NOISE_KEYWORDS: &[&str] = &["$schema", "title", "format", "minimum"];

/// Input schema of a tool: parameter descriptions are kept.
pub fn input_schema<T: JsonSchema + std::any::Any>() -> Arc<JsonObject> {
    let schema = schema_for_input::<T>().unwrap_or_else(|e| {
        panic!(
            "Invalid input schema for `{}`: {}",
            std::any::type_name::<T>(),
            e
        )
    });
    Arc::new(compact(schema.as_ref().clone(), false))
}

/// Output schema of a tool: structure only, field descriptions are dropped
/// (the tool description and the rendered text explain the fields).
pub fn output_schema<T: JsonSchema + std::any::Any>() -> Arc<JsonObject> {
    Arc::new(compact(schema_for_output::<T>().as_ref().clone(), true))
}

fn compact(mut object: JsonObject, drop_descriptions: bool) -> JsonObject {
    strip(&mut object, drop_descriptions);
    inline_single_use_definitions(&mut object);
    object
}

const DEFINITION_PREFIX: &str = "#/$defs/";

/// Replace each `{"$ref": "#/$defs/X"}` whose definition is referenced only
/// once by the definition itself, and drop it from `$defs`.
fn inline_single_use_definitions(root: &mut JsonObject) {
    let Some(Value::Object(mut definitions)) = root.remove("$defs") else {
        return;
    };
    let mut counts = std::collections::HashMap::new();
    count_references(&Value::Object(root.clone()), &mut counts);
    count_references(&Value::Object(definitions.clone()), &mut counts);
    let single: Vec<String> = definitions
        .keys()
        .filter(|name| counts.get(name.as_str()) == Some(&1))
        .cloned()
        .collect();
    let inlined: JsonObject = single
        .iter()
        .filter_map(|name| definitions.remove(name).map(|d| (name.clone(), d)))
        .collect();

    let mut root_value = Value::Object(std::mem::take(root));
    inline_references(&mut root_value, &inlined);
    for definition in definitions.values_mut() {
        inline_references(definition, &inlined);
    }
    if let Value::Object(object) = root_value {
        *root = object;
    }
    if !definitions.is_empty() {
        root.insert("$defs".to_string(), Value::Object(definitions));
    }
}

fn count_references(value: &Value, counts: &mut std::collections::HashMap<String, usize>) {
    match value {
        Value::Object(object) => {
            if let Some(name) = object
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|r| r.strip_prefix(DEFINITION_PREFIX))
            {
                *counts.entry(name.to_string()).or_default() += 1;
            }
            object.values().for_each(|v| count_references(v, counts));
        }
        Value::Array(items) => items.iter().for_each(|v| count_references(v, counts)),
        _ => {}
    }
}

fn inline_references(value: &mut Value, inlined: &JsonObject) {
    match value {
        Value::Object(object) => {
            let target = object
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|r| r.strip_prefix(DEFINITION_PREFIX))
                .and_then(|name| inlined.get(name));
            if let Some(Value::Object(definition)) = target {
                object.remove("$ref");
                for (key, v) in definition {
                    object.entry(key.clone()).or_insert_with(|| v.clone());
                }
            }
            object
                .values_mut()
                .for_each(|v| inline_references(v, inlined));
        }
        Value::Array(items) => items.iter_mut().for_each(|v| inline_references(v, inlined)),
        _ => {}
    }
}

/// Remove noise keywords from a schema object and its subschemas. Property
/// names are data, not keywords: a property called `title` is kept.
fn strip(object: &mut JsonObject, drop_descriptions: bool) {
    for keyword in NOISE_KEYWORDS {
        object.remove(*keyword);
    }
    if drop_descriptions {
        object.remove("description");
    }
    // `["string", "null"]` → `"string"`
    if let Some(Value::Array(types)) = object.get("type")
        && types.len() == 2
        && let Some(position) = types.iter().position(|t| t == "null")
    {
        let kept = types[1 - position].clone();
        object.insert("type".to_string(), kept);
    }
    for (key, value) in object.iter_mut() {
        let is_name_map = matches!(key.as_str(), "properties" | "$defs" | "definitions");
        match value {
            Value::Object(child) if is_name_map => {
                for sub in child.values_mut() {
                    strip_value(sub, drop_descriptions);
                }
            }
            other => strip_value(other, drop_descriptions),
        }
    }
}

fn strip_value(value: &mut Value, drop_descriptions: bool) {
    match value {
        Value::Object(object) => strip(object, drop_descriptions),
        Value::Array(items) => {
            for item in items {
                strip_value(item, drop_descriptions);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_inlines_definitions_used_once() {
        let Value::Object(schema) = json!({
            "type": "object",
            "properties": {
                "file": { "$ref": "#/$defs/File" },
                "up": { "type": "array", "items": { "$ref": "#/$defs/Edge" } },
                "down": { "type": "array", "items": { "$ref": "#/$defs/Edge" } }
            },
            "$defs": {
                "File": { "type": "object", "properties": { "site": { "$ref": "#/$defs/Site" } } },
                "Site": { "type": "object", "properties": { "line": { "type": "integer" } } },
                "Edge": { "type": "object", "properties": { "site": { "$ref": "#/$defs/Site2" } } },
                "Site2": { "type": "string" }
            }
        }) else {
            unreachable!()
        };

        let compacted = Value::Object(compact(schema, true));

        assert_eq!(
            compacted,
            json!({
                "type": "object",
                "properties": {
                    "file": { "type": "object", "properties": { "site": {
                        "type": "object", "properties": { "line": { "type": "integer" } }
                    } } },
                    "up": { "type": "array", "items": { "$ref": "#/$defs/Edge" } },
                    "down": { "type": "array", "items": { "$ref": "#/$defs/Edge" } }
                },
                "$defs": {
                    "Edge": { "type": "object", "properties": { "site": { "type": "string" } } }
                }
            })
        );
    }

    #[test]
    fn test_strip_keeps_properties_named_like_keywords() {
        let Value::Object(schema) = json!({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "kept as a property" },
                "line": { "type": "integer", "format": "uint", "minimum": 0 },
                "limit": { "type": ["integer", "null"] }
            }
        }) else {
            unreachable!()
        };

        let compacted = Value::Object(compact(schema, true));

        assert_eq!(
            compacted,
            json!({
                "type": "object",
                "properties": {
                    "title": { "type": "string" },
                    "line": { "type": "integer" },
                    "limit": { "type": "integer" }
                }
            })
        );
    }
}
